name: raven_dart
version: 0.2.0
author: Yan Cui <theburningmonk@gmail.com>
description: Dart client for Sentry (https://www.getsentry.com)
homepage: https://github.com/theburningmonk/raven-dart
dependencies:
  http: '>=0.11.1+1 <0.12.0'
  uuid: '>=0.5.0 <0.6.0'
dev_dependencies:
  unittest: any
